language: ruby
rvm:
  - 2.3.1
services:
  - mysql
cache: bundler
bundler_args: --without production --deployment
before_script:
  - cp config/database.travis.yml config/database.yml
script:
  - RAILS_ENV=test bundle exec rails db:create --trace
  - bundle exec rails db:migrate --trace
  - bundle exec rspec
